### ISSUE TITLE
Separate game screens into smaller functional components

### ISSUE THREAD

**Issue by Jack-Papel** [mafia-rust/mafia#475]
Our game screens are class components, which are outdated and make it harder to write code quickly. They are also less optimized. Functional components are quick and easy to make, and they're far easier for new contributors to understand -- especially since the react docs for class components are deprecated.

- [x] Chat menu (See #488) 
- [x] Graveyard menu
- [x] Player list menu
- [x] Role-specific menu
  - [x] Amnesiac
  - [x] Consort
  - [x] Doomsayer
  - [x] Forger
  - [x] Journalist
  - [x] Small
- [x] Wiki menu
- [x] Will menu

### Bonus points:
- [x] Play menu (See #477)
- [x] Settings menu
